In [1]:
import turicreate 
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

<h1>1. Reading data</h1>

In [2]:
#Data sourced from https://www.kaggle.com/datasets/hsankesara/medium-articles
data = pd.read_csv("articles.csv")

<h1>2. Exploring data </h1>

In [3]:
data

author claps  reading_time  \
0             Justin Lee  8.3K            11   
1            Conor Dewey  1.4K             7   
2       William Koehrsen  2.8K            11   
3           Gant Laborde  1.3K             7   
4       Emmanuel Ameisen   935            11   
..                   ...   ...           ...   
332       Daniel Simmons  3.4K             8   
333  Eugenio Culurciello  2.8K            13   
334           Devin Soni  5.8K             4   
335      Carlos E. Perez  3.9K             7   
336      Nityesh Agarwal  2.4K            13   

                                                  link  \
0    https://medium.com/swlh/chatbots-were-the-next...   
1    https://towardsdatascience.com/python-for-data...   
2    https://towardsdatascience.com/automated-featu...   
3    https://medium.freecodecamp.org/machine-learni...   
4    https://blog.insightdatascience.com/reinforcem...   
..                                                 ...   
332  https://itnext.io/you-can-build-a-neural-netwo...   
333  https://towardsdatascience.com/artificial-inte...   
334  https://towardsdatascience.com/spiking-neural-...   
335  https://medium.com/intuitionmachine/neurons-ar...   
336  https://towardsdatascience.com/wth-does-a-neur...   

                                                 title  \
0    Chatbots were the next big thing: what happene...   
1    Python for Data Science: 8 Concepts You May Ha...   
2    Automated Feature Engineering in Python – Towa...   
3    Machine Learning: how to go from Zero to Hero ...   
4    Reinforcement Learning from scratch – Insight ...   
..                                                 ...   
332  You can build a neural network in JavaScript e...   
333  Artificial Intelligence, AI in 2018 and beyond...   
334  Spiking Neural Networks, the Next Generation o...   
335  Surprise! Neurons are Now More Complex than We...   
336  “WTH does a neural network even learn??” — a n...   

                                                  text  
0    Oh, how the headlines blared:\nChatbots were T...  
1    If you’ve ever found yourself looking up the s...  
2    Machine learning is increasingly moving from h...  
3    If your understanding of A.I. and Machine Lear...  
4    Want to learn about applied Artificial Intelli...  
..                                                 ...  
332  Click here to share this article on LinkedIn »...  
333  These are my opinions on where deep neural net...  
334  Everyone who has been remotely tuned in to rec...  
335  One of the biggest misconceptions around is th...  
336  I believe, we all have that psychologist/philo...  

[337 rows x 6 columns]

In [4]:
data["author"].unique()

array(['Justin Lee', 'Conor Dewey', 'William Koehrsen', 'Gant Laborde',
       'Emmanuel Ameisen', 'Irhum Shafkat', 'Sam Drozdov',
       'Abhishek Parbhakar', 'Aman Dalmia', 'Sophia Arakelyan',
       'Dr. GP Pulipaka', 'Scott Santens', 'Adam Geitgey', 'Xiaohan Zeng',
       'Gil Fewster', 'David Venturi', 'Michael Jordan', 'Eran Kampf',
       'Oliver Lindberg', 'Xu Wenhao', 'Netflix Technology Blog',
       'Wolf Garbe', 'Paul Christiano', 'Robbie Tilton',
       'James Faghmous ', 'Datafiniti', 'Arjan Haring 🔮🔨', 'Eventbrite',
       'Akash Shende', 'Hrishikesh Huilgolkar', 'Shivon Zilis',
       'AirbnbEng', 'Yingjie Miao ', 'Pinterest Engineering',
       'Nikhil Dandekar', 'Jeff Smith', 'Chris Jagers', 'John Wittenauer',
       'Christopher Nguyen', 'Per Harald Borgen', 'Ahmed El Deeb',
       'Matt Fogel', 'Illia Polosukhin', 'Christophe Bourguignat',
       "I'Boss Potiwarakorn", 'samim', 'Arthur Juliani', 'Tal Perry',
       'Andrej Karpathy', 'Vishal Maini', 'Tim Anglade', '

In [5]:
print(len(data["title"]))
print(len(data["title"].unique()))
#Huh ? How could the titles be same?? Looks like duplicate data?

337
230


In [6]:
data["title"].value_counts()

Simple Reinforcement Learning with Tensorflow Part 0: Q-Learning with Tables and Neural Networks    6
How to easily Detect Objects with Deep Learning on Raspberry Pi                                     5
The $1700 great Deep Learning box: Assembly, setup and benchmarks                                   5
A Brief History of CNNs in Image Segmentation: From R-CNN to Mask R-CNN                             5
Every single Machine Learning course on the internet, ranked by your reviews                        4
                                                                                                   ..
Comparing Artificial Artists – Kyle McDonald – Medium                                               1
Deep Learning Achievements Over the Past Year – Stats and Bots                                      1
What to do with “small” data? – Rants on Machine Learning – Medium                                  1
Announcing Poncho the WeatherBot – Render-from-betaworks                          

In [7]:
data[data['title'] == "Simple Reinforcement Learning with Tensorflow Part 0: Q-Learning with Tables and Neural Networks"]
#Looks like duplicate data

author claps  reading_time  \
59   Arthur Juliani    9K             6   
137  Arthur Juliani    9K             6   
171  Arthur Juliani    9K             6   
283  Arthur Juliani    9K             6   
291  Arthur Juliani    9K             6   
308  Arthur Juliani    9K             6   

                                                  link  \
59   https://medium.com/emergent-future/simple-rein...   
137  https://medium.com/emergent-future/simple-rein...   
171  https://medium.com/emergent-future/simple-rein...   
283  https://medium.com/emergent-future/simple-rein...   
291  https://medium.com/emergent-future/simple-rein...   
308  https://medium.com/emergent-future/simple-rein...   

                                                 title  \
59   Simple Reinforcement Learning with Tensorflow ...   
137  Simple Reinforcement Learning with Tensorflow ...   
171  Simple Reinforcement Learning with Tensorflow ...   
283  Simple Reinforcement Learning with Tensorflow ...   
291  Simple Reinforcement Learning with Tensorflow ...   
308  Simple Reinforcement Learning with Tensorflow ...   

                                                  text  
59   For this tutorial in my Reinforcement Learning...  
137  For this tutorial in my Reinforcement Learning...  
171  For this tutorial in my Reinforcement Learning...  
283  For this tutorial in my Reinforcement Learning...  
291  For this tutorial in my Reinforcement Learning...  
308  For this tutorial in my Reinforcement Learning...

In [8]:
d= data[data['title'] == "Simple Reinforcement Learning with Tensorflow Part 0: Q-Learning with Tables and Neural Networks"]["link"]
pd.options.display.max_colwidth = 200
print(d)
#Ah ! I guess those are not duplicates but different parts of a named series or articles


pd.options.display.max_colwidth = 50
del d

59     https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0?source=tag_archive---------4----------------
137    https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0?source=tag_archive---------5----------------
171    https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0?source=tag_archive---------2----------------
283               https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0?source=---------6----------------
291    https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0?source=tag_archive---------1----------------
308    https://mediu

In [9]:
#how about unique links?

data.link.value_counts()
#No two pages have the same link so that adds up to the fact that there are no duplicates

https://medium.freecodecamp.org/every-single-machine-learning-course-on-the-internet-ranked-by-your-reviews-3c4a7b8026c0?source=tag_archive---------1----------------        1
https://blog.slavv.com/the-1700-great-deep-learning-box-assembly-setup-and-benchmarks-148c5ebe6415?source=tag_archive---------5----------------                              1
https://medium.com/universal-mind/how-i-tracked-my-house-movements-using-ibeacons-3e1e9da3f1a9?source=tag_archive---------3----------------                                  1
https://medium.com/technology-invention-and-more/how-to-build-a-simple-neural-network-in-9-lines-of-python-code-cc8f23647ca1?source=tag_archive---------8----------------    1
https://towardsdatascience.com/how-to-use-noise-to-your-advantage-5301071d9dc3?source=---------4----------------                                                             1
                                                                                                                             

<h1>3. Feature Extraction</h1>
<h3>Generating word count vectors</h3>

In [10]:
#Extracting only the useful features - title, text. More features can be added to the model later on.
newData = data[['title', 'text', 'link']]
print(newData)

                                                 title  \
0    Chatbots were the next big thing: what happene...   
1    Python for Data Science: 8 Concepts You May Ha...   
2    Automated Feature Engineering in Python – Towa...   
3    Machine Learning: how to go from Zero to Hero ...   
4    Reinforcement Learning from scratch – Insight ...   
..                                                 ...   
332  You can build a neural network in JavaScript e...   
333  Artificial Intelligence, AI in 2018 and beyond...   
334  Spiking Neural Networks, the Next Generation o...   
335  Surprise! Neurons are Now More Complex than We...   
336  “WTH does a neural network even learn??” — a n...   

                                                  text  \
0    Oh, how the headlines blared:\nChatbots were T...   
1    If you’ve ever found yourself looking up the s...   
2    Machine learning is increasingly moving from h...   
3    If your understanding of A.I. and Machine Lear...   
4    Want to 

In [11]:
#writing a function that finds words counts from a given text and returns  dictionary of word-count pairs

def retWordCounts(text):
    vectorizer = CountVectorizer()
    X = vectorizer.fit_transform(text)

    counts = dict(zip(vectorizer.get_feature_names(), list(X.toarray()[0]))) #nd now we have a word-count dictonary
    return counts



#retWordCounts([newData.iloc[0].text])[0] #printing only the word-count dictonary
    

In [12]:
newData['wordCounts'] = newData.apply(lambda row: retWordCounts([row.text]), axis = 1) #Only storing the wordCount dictionary in the dataframe
print(newData)

                                                 title  \
0    Chatbots were the next big thing: what happene...   
1    Python for Data Science: 8 Concepts You May Ha...   
2    Automated Feature Engineering in Python – Towa...   
3    Machine Learning: how to go from Zero to Hero ...   
4    Reinforcement Learning from scratch – Insight ...   
..                                                 ...   
332  You can build a neural network in JavaScript e...   
333  Artificial Intelligence, AI in 2018 and beyond...   
334  Spiking Neural Networks, the Next Generation o...   
335  Surprise! Neurons are Now More Complex than We...   
336  “WTH does a neural network even learn??” — a n...   

                                                  text  \
0    Oh, how the headlines blared:\nChatbots were T...   
1    If you’ve ever found yourself looking up the s...   
2    Machine learning is increasingly moving from h...   
3    If your understanding of A.I. and Machine Lear...   
4    Want to 

<ipython-input-12-4008e9310e0c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newData['wordCounts'] = newData.apply(lambda row: retWordCounts([row.text]), axis = 1) #Only storing the wordCount dictionary in the dataframe


<h1>4. Computing TF-IDF for the entire corpus </h1>

In [13]:
#We used the count vector produced earlier to create a word-count tictionary and added it to the table for visualization.
#However, as we need it again to calculate TF-IDF, let's calculate it again
cv = CountVectorizer()
X = cv.fit_transform(newData.text)
print(X.shape)


(337, 20396)


In [14]:
tfTransformer = TfidfTransformer()
tfidf = tfTransformer.fit_transform(X)
print(tfidf.shape)

(337, 20396)


In [15]:
words = cv.get_feature_names()
tfidfVals = tfidf.toarray()

In [16]:
print(tfidfVals)

[[0.         0.01116781 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


<h1 >4.1 A faster way using Pipelines<h6>(faster to code)</h6></h1>

In [17]:
from sklearn.pipeline import Pipeline
import numpy as np

In [18]:
pipe = Pipeline([('count', CountVectorizer()),
                ('tfidf', TfidfTransformer())
                ])

In [19]:
newData

title  \
0    Chatbots were the next big thing: what happene...   
1    Python for Data Science: 8 Concepts You May Ha...   
2    Automated Feature Engineering in Python – Towa...   
3    Machine Learning: how to go from Zero to Hero ...   
4    Reinforcement Learning from scratch – Insight ...   
..                                                 ...   
332  You can build a neural network in JavaScript e...   
333  Artificial Intelligence, AI in 2018 and beyond...   
334  Spiking Neural Networks, the Next Generation o...   
335  Surprise! Neurons are Now More Complex than We...   
336  “WTH does a neural network even learn??” — a n...   

                                                  text  \
0    Oh, how the headlines blared:\nChatbots were T...   
1    If you’ve ever found yourself looking up the s...   
2    Machine learning is increasingly moving from h...   
3    If your understanding of A.I. and Machine Lear...   
4    Want to learn about applied Artificial Intelli...   
..                                                 ...   
332  Click here to share this article on LinkedIn »...   
333  These are my opinions on where deep neural net...   
334  Everyone who has been remotely tuned in to rec...   
335  One of the biggest misconceptions around is th...   
336  I believe, we all have that psychologist/philo...   

                                                  link  \
0    https://medium.com/swlh/chatbots-were-the-next...   
1    https://towardsdatascience.com/python-for-data...   
2    https://towardsdatascience.com/automated-featu...   
3    https://medium.freecodecamp.org/machine-learni...   
4    https://blog.insightdatascience.com/reinforcem...   
..                                                 ...   
332  https://itnext.io/you-can-build-a-neural-netwo...   
333  https://towardsdatascience.com/artificial-inte...   
334  https://towardsdatascience.com/spiking-neural-...   
335  https://medium.com/intuitionmachine/neurons-ar...   
336  https://towardsdatascience.com/wth-does-a-neur...   

                                            wordCounts  
0    {'000': 1, '100': 1, '16': 1, '1990s': 1, '200...  
1    {'30': 1, 'ability': 1, 'about': 2, 'above': 2...  
2    {'793': 1, 'about': 3, 'above': 1, 'absolutely...  
3    {'100': 1, '11': 1, '1936': 1, 'able': 2, 'abo...  
4    {'360': 1, '3d': 1, '49': 1, 'a2c': 1, 'about'...  
..                                                 ...  
332  {'000': 1, '10': 1, '11': 1, '20': 1, '25': 1,...  
333  {'100x': 1, '20': 1, '2008': 1, '2012': 1, '99...  
334  {'100': 1, '2nd': 4, '3rd': 1, '50': 1, 'abili...  
335  {'02627v1': 1, '10x': 1, '125': 1, '1802': 1, ...  
336  {'10': 6, '100': 1, '10000': 1, '11': 1, '14to...  

[337 rows x 4 columns]

In [20]:
pipe.fit(newData.text)

Pipeline(steps=[('count', CountVectorizer()), ('tfidf', TfidfTransformer())])

In [21]:
countFromPipe = pipe['count'].transform(newData.text).toarray()
print(countFromPipe)



[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
pipeTfidf = pipe['tfidf'].transform(countFromPipe).toarray()
print(pipeTfidf)

del pipeTfidf
del countFromPipe

[[0.         0.01116781 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [23]:
pipeFinal = pipe.transform(newData.text).toarray()
print(pipeFinal)


[[0.         0.01116781 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [24]:
finalTfidfsAndWords= list(pipeFinal.copy())
words = cv.get_feature_names()

for i in range(0, len(finalTfidfsAndWords)):
    a = list(zip(words, finalTfidfsAndWords[i]))
    finalTfidfsAndWords[i] =   list(sorted(a, key = lambda x: x[1], reverse= True))
    
del a

In [25]:
(len(finalTfidfsAndWords), len(finalTfidfsAndWords[0]))

(337, 20396)

In [26]:
finalTfidfsAndWords[125]

[('pac', 0.5025648346317365),
 ('the', 0.39676387354479986),
 ('man', 0.30474045535660993),
 ('ms', 0.19893191370839575),
 ('ghosts', 0.18741002471542592),
 ('of', 0.16759054956349853),
 ('to', 0.16176727132860672),
 ('game', 0.13806114146860116),
 ('in', 0.13722056087186782),
 ('and', 0.11463523377912975),
 ('that', 0.1104280811788612),
 ('lucas', 0.11024119100907406),
 ('is', 0.10163409568635268),
 ('games', 0.09517144513313312),
 ('research', 0.08855984288488225),
 ('ghost', 0.08819295280725925),
 ('behaviour', 0.08354392243090754),
 ('proceedings', 0.08221713563327568),
 ('evolutionary', 0.07834956526784624),
 ('ieee', 0.07751404537599264),
 ('competition', 0.07320595051642059),
 ('on', 0.06764359043217116),
 ('this', 0.0674030297202528),
 ('it', 0.066847504894785),
 ('for', 0.06664998670919293),
 ('pacman', 0.06614471460544444),
 ('computational', 0.061666553889192934),
 ('an', 0.057211395738187835),
 ('player', 0.055472635417412396),
 ('ai', 0.055369443557359385),
 ('midway', 0.0

<h1>5. Comparing the results </h1>

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
similar_doc1 = pipeFinal[308].reshape(1, -1) #Simple Reinforcement learning Part 1
similar_doc2 = pipeFinal[291].reshape(1, -1) #Simple Reinforcement learning Part 2


cosine_similarity(similar_doc1, similar_doc2)
#a similarity of 1!! Very similar !!!

array([[1.]])

In [29]:
similar_doc1 = pipeFinal[0].reshape(1, -1) #An Article on chatbots
similar_doc2 = pipeFinal[1].reshape(1, -1) #An article on Python for Data science


cosine_similarity(similar_doc1, similar_doc2)
#Hmm... not very similar. Makes sense.

array([[0.43593557]])

<h1>6. Building a k-means clustering model to find 'k' nearest documents</h1>

In [30]:
from sklearn.neighbors import NearestNeighbors

In [31]:
neigh = NearestNeighbors()
neigh.fit(pipeFinal)

NearestNeighbors()

In [32]:
print(newData.iloc[0].title)
print(newData.iloc[291].title)

Chatbots were the next big thing: what happened? – The Startup – Medium
Simple Reinforcement Learning with Tensorflow Part 0: Q-Learning with Tables and Neural Networks


In [33]:
#10 articles similar to article 0 - "Chatbots were the next big thing: what happened? – The Startup – Medium"
indices = neigh.kneighbors(n_neighbors= 10, X = pipeFinal[0].reshape(1,-1))[1]
newData.iloc[indices[0]]

#Notice how the titles are same for some of the articles. As we found out during data exploration,
#they're all part of a series of articles.

title  \
273  Chatbots were the next big thing: what happene...   
86   Chatbots were the next big thing: what happene...   
0    Chatbots were the next big thing: what happene...   
189  Deep Learning the Stock Market – Tal Perry – M...   
141  Deep Learning the Stock Market – Tal Perry – M...   
62   Deep Learning the Stock Market – Tal Perry – M...   
192  Ultimate Guide to Leveraging NLP & Machine Lea...   
266  Deep Learning Achievements Over the Past Year ...   
217  The beginner’s guide to conversational commerc...   
132  Start automating your business tasks with Slac...   

                                                  text  \
273  Oh, how the headlines blared:\nChatbots were T...   
86   Oh, how the headlines blared:\nChatbots were T...   
0    Oh, how the headlines blared:\nChatbots were T...   
189  Update 25.1.17 — Took me a while but here is a...   
141  Update 25.1.17 — Took me a while but here is a...   
62   Update 25.1.17 — Took me a while but here is a...   
192  Code Snippets and Github Included\nOver the pa...   
266  At Statsbot, we’re constantly reviewing the de...   
217  Your greengrocer does it. So does that guy sel...   
132  If you haven’t read about it in the Times or h...   

                                                  link  \
273  https://medium.com/swlh/chatbots-were-the-next...   
86   https://medium.com/swlh/chatbots-were-the-next...   
0    https://medium.com/swlh/chatbots-were-the-next...   
189  https://medium.com/@TalPerry/deep-learning-the...   
141  https://medium.com/@TalPerry/deep-learning-the...   
62   https://medium.com/@TalPerry/deep-learning-the...   
192  https://chatbotslife.com/ultimate-guide-to-lev...   
266  https://blog.statsbot.co/deep-learning-achieve...   
217  https://medium.com/swlh/the-beginners-guide-to...   
132  https://blog.howdy.ai/what-will-the-automated-...   

                                            wordCounts  
273  {'000': 1, '100': 1, '16': 1, '1990s': 1, '200...  
86   {'000': 1, '100': 1, '16': 1, '1990s': 1, '200...  
0    {'000': 1, '100': 1, '16': 1, '1990s': 1, '200...  
189  {'10': 1, '100': 1, '1000': 2, '10x': 1, '11':...  
141  {'10': 1, '100': 1, '1000': 2, '10x': 1, '11':...  
62   {'10': 1, '100': 1, '1000': 2, '10x': 1, '11':...  
192  {'000': 3, '01': 1, '02': 1, '03': 1, '08': 1,...  
266  {'000': 1, '100': 2, '150': 1, '17': 1, '20': ...  
217  {'10x': 1, '15': 1, '1999': 1, '2007': 1, '201...  
132  {'10': 1, '13': 1, '15': 1, '2008': 1, '90': 3...

In [34]:
pd.options.display.max_colwidth = 200

#Let's chek their links to confirm
print(newData.iloc[indices[0]][:3].link)

#Parts 0, 1, 6. They arn't the same.
pd.options.display.max_colwidth = 50

273    https://medium.com/swlh/chatbots-were-the-next-big-thing-what-happened-5fc49dd6fa61?source=tag_archive---------6----------------
86                https://medium.com/swlh/chatbots-were-the-next-big-thing-what-happened-5fc49dd6fa61?source=---------1----------------
0                 https://medium.com/swlh/chatbots-were-the-next-big-thing-what-happened-5fc49dd6fa61?source=---------0----------------
Name: link, dtype: object


In [35]:
#10 articles similar to the article with title "Simple Reinforcement Learning with Tensorflow Part 0: Q-Learning with Tables and Neural Networks"
#THe article in subject is in iloc 291
indices = neigh.kneighbors(n_neighbors= 10, X = pipeFinal[291].reshape(1,-1))[1]
newData.iloc[indices[0]]


title  \
283  Simple Reinforcement Learning with Tensorflow ...   
171  Simple Reinforcement Learning with Tensorflow ...   
291  Simple Reinforcement Learning with Tensorflow ...   
308  Simple Reinforcement Learning with Tensorflow ...   
137  Simple Reinforcement Learning with Tensorflow ...   
59   Simple Reinforcement Learning with Tensorflow ...   
157  Reinforcement Learning from scratch – Insight ...   
4    Reinforcement Learning from scratch – Insight ...   
88   Reinforcement Learning from scratch – Insight ...   
195  Simple Reinforcement Learning with Tensorflow ...   

                                                  text  \
283  For this tutorial in my Reinforcement Learning...   
171  For this tutorial in my Reinforcement Learning...   
291  For this tutorial in my Reinforcement Learning...   
308  For this tutorial in my Reinforcement Learning...   
137  For this tutorial in my Reinforcement Learning...   
59   For this tutorial in my Reinforcement Learning...   
157  Want to learn about applied Artificial Intelli...   
4    Want to learn about applied Artificial Intelli...   
88   Want to learn about applied Artificial Intelli...   
195  Welcome to the latest installment of my Reinfo...   

                                                  link  \
283  https://medium.com/emergent-future/simple-rein...   
171  https://medium.com/emergent-future/simple-rein...   
291  https://medium.com/emergent-future/simple-rein...   
308  https://medium.com/emergent-future/simple-rein...   
137  https://medium.com/emergent-future/simple-rein...   
59   https://medium.com/emergent-future/simple-rein...   
157  https://blog.insightdatascience.com/reinforcem...   
4    https://blog.insightdatascience.com/reinforcem...   
88   https://blog.insightdatascience.com/reinforcem...   
195  https://medium.com/@awjuliani/simple-reinforce...   

                                            wordCounts  
283  {'16': 1, '16x4': 2, '1x16': 1, '4x4': 1, 'abo...  
171  {'16': 1, '16x4': 2, '1x16': 1, '4x4': 1, 'abo...  
291  {'16': 1, '16x4': 2, '1x16': 1, '4x4': 1, 'abo...  
308  {'16': 1, '16x4': 2, '1x16': 1, '4x4': 1, 'abo...  
137  {'16': 1, '16x4': 2, '1x16': 1, '4x4': 1, 'abo...  
59   {'16': 1, '16x4': 2, '1x16': 1, '4x4': 1, 'abo...  
157  {'360': 1, '3d': 1, '49': 1, 'a2c': 1, 'about'...  
4    {'360': 1, '3d': 1, '49': 1, 'a2c': 1, 'about'...  
88   {'360': 1, '3d': 1, '49': 1, 'a2c': 1, 'about'...  
195  {'2014': 2, '50': 1, '5x5': 1, '84x84x3': 1, '...